name: 'fmn_fmcg_data_pipeline'
version: '1.0.0'
config-version: 2

# THIS MUST MATCH THE NAME IN PROFILES.YML
profile: 'fmcg_pipeline_profile' 

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  fmn_fmcg_data_pipeline:
    # This ensures all models in the models/ directory are built as tables by default
    +materialized: table